runtime: php74

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:jKeYerdchuIHUeD1PwVuI8DH2pNmo1D3Jb7lYQl8u5c=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie